// Package marker makes GitHub's authoritative `archived` flag visible on the
// local filesystem.
//
// The archived state of a repository lives in GitHub metadata, which is invisible
// to anyone (human or LLM agent) working from a local clone. Agents therefore fall
// back to grepping READMEs — an inconsistent, noisy signal. This package closes
// that gap: for every archived repo that exists locally, repoTrawl writes two
// conspicuous, untracked marker files into the clone root:
//
//	ARCHIVED.md  — a human/LLM-readable banner (sorts to the top of a listing)
//	.archived    — a minimal machine-readable key=value file for cheap checks
//
// The markers are UNTRACKED: they are added to .git/info/exclude (inside a managed
// block) so they never dirty the working tree and never need to be committed
// (archived repos are read-only on GitHub anyway). Propagation across the lab is
// via the repoTrawl binary, not git: every member who runs a marker-aware
// repoTrawl regenerates the markers locally from the same authoritative GitHub
// flag. The reconcile is self-healing in both directions — un-archiving a repo
// removes its markers (and the exclude block) on the next run.
//
// Safety: repoTrawl only ever writes, refreshes, or removes files that carry its
// own sentinel. A pre-existing user/tracked file named ARCHIVED.md or .archived is
// never overwritten or deleted; the repo is reported as skipped instead.
package marker

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// File names written into an archived clone's root.
const (
	MarkerFile = "ARCHIVED.md"
	DotFile    = ".archived"
)

// Sentinels that identify a repoTrawl-generated marker (a stable substring of the
// rendered content). A file lacking its sentinel is treated as foreign and is
// never overwritten or removed.
const (
	mdSentinel  = "generated locally by repoTrawl"
	dotSentinel = "marker=repoTrawl/"
)

// Managed block delimiters for the .git/info/exclude entries, so the block can be
// added and later removed without touching any unrelated exclude lines.
const (
	excludeBegin = "# >>> repoTrawl archive markers (managed) >>>"
	excludeEnd   = "# <<< repoTrawl archive markers (managed) <<<"
)

// State describes a repo's archive status and where (if anywhere) it is cloned.
type State struct {
	Name         string
	Dir          string // local clone path; empty / non-existent dirs are skipped
	Archived     bool
	LastActivity string // ISO-8601 pushed_at, a best-effort "last activity" proxy
}

// Action records what Reconcile did for one repo.
type Action string

const (
	ActionMarked   Action = "marked"   // wrote/updated the archived markers
	ActionUnmarked Action = "unmarked" // removed stale markers (repo un-archived)
	ActionSkipped  Action = "skipped"  // a foreign file blocked a marker write
	ActionNoop     Action = "noop"     // already in the desired state
	ActionError    Action = "error"
)

// Result is the outcome for a single repo (noops are omitted by Reconcile).
type Result struct {
	Name   string
	Action Action
	Err    error
}

// Reconcile writes or removes the archive markers for each cloned repo so that
// GitHub's `archived` flag becomes visible locally. It only touches real git
// clones and only ever modifies files carrying repoTrawl's own sentinel; it is
// idempotent and returns the non-noop outcomes.
func Reconcile(states []State, version string) []Result {
	var results []Result
	for _, s := range states {
		if s.Dir == "" || !isGitDir(s.Dir) {
			// Not a normal clone (missing, or .git is a file/worktree): never write
			// markers we cannot also exclude — that would dirty the tree.
			continue
		}
		var (
			act Action
			err error
		)
		if s.Archived {
			act, err = ensureMarked(s, version)
		} else {
			act, err = ensureUnmarked(s.Dir)
		}
		switch {
		case err != nil:
			results = append(results, Result{Name: s.Name, Action: ActionError, Err: err})
		case act != ActionNoop:
			results = append(results, Result{Name: s.Name, Action: act})
		}
	}
	return results
}

// isGitDir reports whether dir contains a real .git directory (not a gitdir file
// used by worktrees/submodules, where we cannot reliably manage info/exclude).
func isGitDir(dir string) bool {
	fi, err := os.Stat(filepath.Join(dir, ".git"))
	return err == nil && fi.IsDir()
}

// ensureMarked adds the managed exclude block, then writes the two marker files.
// It is all-or-nothing with respect to pre-existing foreign files: if EITHER
// target exists and was not generated by repoTrawl (no sentinel), nothing is
// touched — not the exclude file, not the sibling marker — and the repo is
// reported as ActionSkipped.
func ensureMarked(s State, version string) (Action, error) {
	files := []struct{ path, content, sentinel string }{
		{filepath.Join(s.Dir, MarkerFile), renderMarkdown(s, version), mdSentinel},
		{filepath.Join(s.Dir, DotFile), renderDotfile(s, version), dotSentinel},
	}

	// Preflight: refuse to act if either marker path holds a foreign file.
	for _, f := range files {
		foreign, err := isForeign(f.path, f.sentinel)
		if err != nil {
			return ActionError, err
		}
		if foreign {
			return ActionSkipped, nil
		}
	}

	// Manage the exclude block FIRST; if we cannot, do not write markers (keeps the
	// "never dirty the working tree" guarantee).
	if err := ensureExcludeBlock(s.Dir); err != nil {
		return ActionError, fmt.Errorf("update .git/info/exclude: %w", err)
	}

	changed := false
	for _, f := range files {
		wrote, err := writeMarkerFile(f.path, f.content)
		if err != nil {
			return ActionError, err
		}
		changed = changed || wrote
	}
	if changed {
		return ActionMarked, nil
	}
	return ActionNoop, nil
}

// ensureUnmarked removes repoTrawl-generated markers and the managed exclude block
// when a repo is un-archived. Foreign files of the same name are left untouched.
func ensureUnmarked(dir string) (Action, error) {
	removed := false
	for _, f := range []struct{ name, sentinel string }{
		{MarkerFile, mdSentinel},
		{DotFile, dotSentinel},
	} {
		gone, err := removeMarkerFile(filepath.Join(dir, f.name), f.sentinel)
		if err != nil {
			return ActionError, err
		}
		removed = removed || gone
	}
	blockGone, err := removeExcludeBlock(dir)
	if err != nil {
		return ActionError, err
	}
	if removed || blockGone {
		return ActionUnmarked, nil
	}
	return ActionNoop, nil
}

// isForeign reports whether path exists and was NOT generated by repoTrawl (its
// sentinel substring is absent). A missing file is not foreign.
func isForeign(path, sentinel string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	return !strings.Contains(string(data), sentinel), nil
}

// writeMarkerFile writes content to path when it is absent or stale. The caller
// must have already verified the file is not foreign (see isForeign).
func writeMarkerFile(path, content string) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
		return false, nil // already current
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// removeMarkerFile removes path only when it exists and is repoTrawl-generated.
func removeMarkerFile(path, sentinel string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, nil // absent (or unreadable) — nothing to do
	}
	if !strings.Contains(string(data), sentinel) {
		return false, nil // foreign file — leave it
	}
	if err := os.Remove(path); err != nil {
		return false, err
	}
	return true, nil
}

func renderMarkdown(s State, version string) string {
	return fmt.Sprintf(`ARCHIVED — DO NOT USE

This repository is ARCHIVED on GitHub (read-only) and is excluded from active lab
work. Agents and lab members: treat it as stale. Do not edit it, build on it, or
cite it as current. If a superseding repository exists, prefer it (see this repo's
README).

    archived:       true
    last_activity:  %s
    source:         github.com archived flag
    marker:         repoTrawl %s

This file is %s from GitHub's archived flag; it is not committed (git-ignored via
.git/info/exclude). Re-run repoTrawl to refresh it, or it is removed automatically
if the repository is un-archived.
`, lastActivity(s), version, mdSentinel)
}

func renderDotfile(s State, version string) string {
	return fmt.Sprintf("archived=true\nlast_activity=%s\nsource=github\n%s%s\n", lastActivity(s), dotSentinel, version)
}

func lastActivity(s State) string {
	if s.LastActivity == "" {
		return "unknown"
	}
	return s.LastActivity
}

// ensureExcludeBlock adds the managed marker block to <dir>/.git/info/exclude when
// a complete block is not already present, newline-safe (never concatenates onto a
// prior line). A partial/corrupt managed block (only one delimiter, or out of
// order) is stripped and rewritten so we never leave markers that aren't excluded.
func ensureExcludeBlock(dir string) error {
	infoDir := filepath.Join(dir, ".git", "info")
	if err := os.MkdirAll(infoDir, 0o755); err != nil {
		return err
	}
	excludePath := filepath.Join(infoDir, "exclude")

	existing, _ := os.ReadFile(excludePath)
	text := string(existing)
	begin := strings.Index(text, excludeBegin)
	end := strings.Index(text, excludeEnd)
	if begin >= 0 && end > begin {
		return nil // a complete managed block is already present
	}
	if begin >= 0 || end >= 0 {
		// Partial/corrupt managed block — strip it before re-appending a clean one.
		if _, err := removeExcludeBlock(dir); err != nil {
			return err
		}
		existing, _ = os.ReadFile(excludePath)
	}

	var b strings.Builder
	b.Write(existing)
	// Ensure separation from any prior content that lacks a trailing newline.
	if len(existing) > 0 && !strings.HasSuffix(string(existing), "\n") {
		b.WriteString("\n")
	}
	b.WriteString(excludeBegin + "\n")
	b.WriteString("/" + MarkerFile + "\n")
	b.WriteString("/" + DotFile + "\n")
	b.WriteString(excludeEnd + "\n")
	return os.WriteFile(excludePath, []byte(b.String()), 0o644)
}

// removeExcludeBlock strips the managed marker block from .git/info/exclude,
// leaving all unrelated lines intact. The end delimiter is searched only AFTER the
// begin delimiter; a dangling begin (no matching end) is trimmed to end-of-file.
// Returns whether anything was removed.
func removeExcludeBlock(dir string) (bool, error) {
	excludePath := filepath.Join(dir, ".git", "info", "exclude")
	data, err := os.ReadFile(excludePath)
	if err != nil {
		return false, nil // no exclude file — nothing to do
	}
	text := string(data)
	start := strings.Index(text, excludeBegin)
	if start < 0 {
		return false, nil
	}
	endRel := strings.Index(text[start:], excludeEnd)
	var end int
	if endRel < 0 {
		end = len(text) // dangling begin: drop the remnant to EOF
	} else {
		end = start + endRel + len(excludeEnd)
		if end < len(text) && text[end] == '\n' {
			end++ // also drop the block's trailing newline
		}
	}
	cleaned := text[:start] + text[end:]
	return true, os.WriteFile(excludePath, []byte(cleaned), 0o644)
}
